# Generated by Django 4.2.11 on 2024-05-08 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('room_pictures', models.ImageField(upload_to='room_pictures', verbose_name='Room Pictures')),
                ('card_description', models.CharField(max_length=255, verbose_name='Card Description')),
                ('room_description', models.TextField(verbose_name='Room Description')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Check-in Date')),
                ('check_out', models.DateField(verbose_name='Check-out Date')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Guest Name')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Guest Email')),
                ('guest_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Guest Phone')),
                ('num_guests', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Number of Guests')),
                ('dog', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Number of Dogs')),
                ('vehicle', models.BooleanField(default=False, verbose_name='Vehicle')),
                ('guest_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Reservation Date')),
                ('reservation_status', models.BooleanField(default=False, verbose_name='Reservation Status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room', verbose_name='Reserved Room')),
            ],
        ),
    ]
