# Generated by Django 4.2.11 on 2024-05-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dog',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Dog'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_pictures',
            field=models.ImageField(upload_to='static/images/room_pictures', verbose_name='Room Pictures'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='images',
            field=models.ImageField(upload_to='static/images/room_pictures', verbose_name='Room Pictures'),
        ),
    ]
